### PR TITLE
started griddap notebook

### LINKED ISSUE #191: griddap documentation
Where should we document the griddap capability? The "longer introduction" notebook? A notebook of its own?

### PR DESCRIPTION
**Pull request by callumrollo**
This will eventually close #191 need to figure out how the notebook becomes part of the documentation first though

### CODE REVIEW

**Comment by callumrollo** [comment]
Same problem with failing tests over here, independent commit, not even touching the erddapy code. Something must be up with the CI

**Comment by ocefpaf** [comment]
I opened an issue upstream to track this. See https://github.com/s-weigand/setup-conda/issues/125

**Comment by s-weigand** [comment]
I just release `v1.0.7`, so using `s-weigand/setup-conda@v1` should be fine again.
Thanks again for reporting the issue and testing the fix branch ❤️

**Comment by callumrollo** [comment]
@ocefpaf the notebook is still pretty detail-light, but it covers essential griddap functionality, including a plot and how to skip the sub-setting by using opendap.

If I've got the sphinx integration right, I think we're about done with this PR

**Comment by callumrollo** [comment]
All green lights bay-beee!

**Comment by callumrollo** [comment]
Is it ok for me to add GSoC labels? Feels kinda like marking my one homework...

**Comment by ocefpaf** [comment]
> Is it ok for me to add GSoC labels? Feels kinda like marking my one homework...

Please do! I may forget. Also, that is not marking, the marking comes after ;-p

**Comment by ocefpaf** [comment]
@callumrollo I messed up the rebase b/c I still had a `master` branch and pulled stuff from it. Sorry! Do you mind re-sending this PR? It is probably the cleanest way to preserve your commits/authorship here.

**Comment by callumrollo** [comment]
No worries @ocefpaf, I'll do that now

**Pull request closed without merging**
