### PR TITLE
fixes 137

### PR DESCRIPTION
**Pull request by ocefpaf**
@abkfenris this was broken since I added the in-memory netCDF. However, the real mystery here is why the in-memory stopped working on that server. I'm still investigating that b/c I want to add tests for both cases.

### CODE REVIEW

**Comment by abkfenris** [comment]
I suggest [VCRpy](https://vcrpy.readthedocs.io/en/latest/) for catching fixtures of issues like this, so you don't have to depend on the server to keep making the same mistake on demand.

I usually set it up so it doesn't have to match quite so strictly

https://github.com/gulfofmaine/buoy_barn/blob/56aec9ce3d7a40b6ad85b4b9a7f53bb813a7f897/app/deployments/tests/vcr.py#L1-L4

Then decorate the test.

https://github.com/gulfofmaine/buoy_barn/blob/master/app/deployments/tests/test_tasks.py#L116-L124

[pytest-vcr](https://pytest-vcr.readthedocs.io/en/latest/) also can give you a little more pytestish interface.

I had been thinking about going through and adding VCR tests at some point. pytest-vcr might be nice because you can also do a test run with test disabled quickly.

**Comment by ocefpaf** [comment]
Yep. +1 to vcrpy!

**Comment by ocefpaf** [comment]
BTW, in-memory is working again for that server but the fix here is still necessary for the cases when it will fail. I'll leave the addition of better test with vcr to another PR.

**Comment by ocefpaf** [comment]
> I'll leave the addition of better test with vcr to another PR.

Actually it was easier than I thought with pytest-vcr.

**Pull request merged**
