### PR TITLE
Add Python 3.11 support

### PR DESCRIPTION
**Pull request by abkfenris**
Starts testing against Python 3.11 and adds a classifier for it.

### CODE REVIEW

**Comment by abkfenris** [comment]
Hmm, micromamba env setup is failing because it's [trying to use a Python 2.7 package](https://github.com/ioos/erddapy/actions/runs/3341325526/jobs/5532423985#step:4:22). It's not however failing appropriately on that step, which is probably a micromamba issue.

**Comment by ocefpaf** [comment]
It is missing a mypy dependency on py3.11 micromamba is failing to fail in the env creation.

**Comment by abkfenris** [comment]
Now its succeeding to fail on env creation.

**Comment by ocefpaf** [comment]
mypy is available but now iris is the blocker.

**Pull request merged**
